### ISSUE TITLE
null safe library

### ISSUE THREAD

**Issue by Dimitry82** [adityadees/flutter_profile_picture#6]
The library 'package:flutter_profile_picture/flutter_profile_picture.dart' is legacy, and should not be imported into a null safe library.  Try migrating the imported library.

**Comment by fernandoe321** [comment]
> The library 'package:flutter_profile_picture/flutter_profile_picture.dart' is legacy, and should not be imported into a null safe library. Try migrating the imported library.

Haven't tried yet it but this seems like the only way for now to use non-null safe packages in null-safe apps or packages
https://dart.dev/null-safety/unsound-null-safety

**Comment by pm489** [comment]
Heya I bumped into this issue today - so I have raised a PR just now to try and migrate it over.
